### ISSUE TITLE
Activité Partielle - Indication qu'il s'agit de cumul

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/dashboard-aides-entreprises#129]
Plusieurs demandes sur l'origine et la signification des données.
- indiquer qu'il s'agit de cumul
- informer dans la partie textuelle qu'il s'agit des données produites par la DARES et mettre le lien des données
- peut-être supprimer JDD Etalab qui n'apporte pas grand chose.

**Comment by JulienParis** [comment]
ajout d'un bloc de texte entre les chiffres et le titre du premier graphique

> nota : les chiffres indiqués représentent les valeurs cumulées depuis le début de la crise sanitaire COVID-19

**Comment by geoffreyaldebert** [comment]
Plus d'informations sur la prise en charge de l'activité partielle sur la page des FAQ ainsi que sur le portail officiel .
=>
Ces données sont tirées des tableaux de bords mis en place par la DARES. Plus d'informations sur le portail de la DARES (lien : https://dares.travail-emploi.gouv.fr/dares-etudes-et-statistiques/tableaux-de-bord/le-marche-du-travail-pendant-le-covid-19/tableaux-de-bord-hebdomadaires/) ainsi que sur le portail officiel (lien actuel)

**Comment by JulienParis** [comment]
done in https://github.com/etalab/dashboard-aides-entreprises/commit/9af47c724f9ab1fb9c3400baec7cd53e5ee76e67
