### ISSUE TITLE
perfs build front

### ISSUE THREAD

**Issue by JulienParis** [etalab/dashboard-aides-entreprises#42]
Pistes d'amélioration : 

- [x] cibler les fonts à charger (fontawesome ds le css)
- [x] réduire la place de `vendors` dans le build
- [x] ne pas inclure les geojson dans le build / enlever des statics => load depuis le composant mapbox ? 
- [x] gicler les composants inutiles ?

**Comment by JulienParis** [comment]
Ref pour test : https://github.com/nuxt/nuxt.js/issues/2201

**Comment by JulienParis** [comment]
- treeshake vuetify ?
- treeshake fontawesome / mdi icons ?
- ...

**Comment by JulienParis** [comment]
Cf https://medium.com/@kozyreva.hanna/nuxt-js-fontawesome-integration-7ec56b1a41c8

**Comment by JulienParis** [comment]
Cf https://blog.webjeda.com/optimize-fontawesome/

**Comment by JulienParis** [comment]
Cf https://stackoverflow.com/questions/59263711/vuetify-automatic-treeshaking-in-nuxt-js

**Comment by abulte** [comment]
Les départements et les régions à 1000m devraient être dispo très bientôt sur http://etalab-datasets.geo.data.gouv.fr/contours-administratifs/latest/geojson/ 🎉

**Comment by abulte** [comment]
Dispo ⏫

**Comment by JulienParis** [comment]
PR ici pour l'intégration des geojsons 1000 => https://github.com/etalab/dashboard-aides-entreprises/pull/61

preview ici => https://deploy-preview-61--aides-entreprises-covid19.netlify.app/

J'en ai profité pour supprimer les geojson 100m des statics... On pourrait même bientôt tous les virer des statics pour n'aller pointer que vers les fichiers à la racine du repo

**Comment by abulte** [comment]
> On pourrait même bientôt tous les virer des statics pour n'aller pointer que vers les fichiers à la racine du repo

Donc passer par Github et pas par Netlify ? On peut se retrouver à taper une limite Github qu'on a pas (pour le moment) sur Netlify si on fait beaucoup de trafic.

**Comment by JulienParis** [comment]
<img width="1089" alt="Capture d’écran 2020-05-06 à 12 13 21" src="https://user-images.githubusercontent.com/21986727/81165906-1ac05c00-8f93-11ea-9c5a-94484de8c30c.png">

**Comment by JulienParis** [comment]
bon c'est pas horrible non plus après le linting... le plus gros est évidemment dans les modules vuetify / mapboxgl / apexcharts ... je suis en train de tester en allégeant un peu le `main.sass` en enlevant les fonts materialdesigns qu'on n'utilise pas
... je peux même tenter d'alléger encore un peu plus côté fonts en ne chargeant que les 3 icones dont on a besoin au lieu de tt fontawesome ...

**Comment by JulienParis** [comment]
bon gros lifting avec cette PR => https://github.com/etalab/dashboard-aides-entreprises/pull/64 

@abulte je pense fermer cette issue pour clore ce round d'optim
