### ISSUE TITLE
bug IE !!!

### ISSUE THREAD

**Issue by JulienParis** [etalab/dashboard-aides-entreprises#43]

**Comment by JulienParis** [comment]
bravo à @abulte pour ton flair et avoir débusqué notre Kaiser Susie du jour => https://github.com/etalab/dashboard-aides-entreprises/pull/46

**Comment by JulienParis** [comment]
pour mémoire le problème était de transpiler le module `vue-mapbox`

**Comment by abulte** [comment]
https://media.giphy.com/media/1xOQlQxrIX4Jw6lBZI/giphy.gif
