### ISSUE TITLE
liens des titres de graphiques vers définitions des référentiels

### ISSUE THREAD

**Issue by JulienParis** [etalab/dashboard-aides-entreprises#66]
sur le même modèle que le lien `code section NAF` mettre dans les titres des graphiques les liens vers les pages de définition officielles des :

- [ ] catégories juridiques
- [ ] classes d'effectifs

**Comment by JulienParis** [comment]
@geoffreyaldebert pour te simplifier la vie, si tu me passes juste les liens je me chargerai de les mettre dans les textes

**Comment by geoffreyaldebert** [comment]
Catégorie juridique : tu peux mettre un lien vers : https://www.insee.fr/fr/information/2028129
Classe effectif j'ai trouvé ça : https://www.insee.fr/fr/information/1896448

**Comment by JulienParis** [comment]
ok c'est intégré, je ferme l'issue alors
