### ISSUE TITLE
écrire le texte d'infos relatif au JDD "reports d'échéances"

### ISSUE THREAD

**Issue by JulienParis** [etalab/dashboard-aides-entreprises#67]
idem @romtal mais sur le sujet des reports d'échéances

**Comment by JulienParis** [comment]
@romtal du neuf sur les textes relatifs aux reports d'échéance ? Je suis en train d'intégrer tout ça en preprod

**Comment by romtal** [comment]
Le Gouvernement a annoncé le report des principales échéances fiscales des professionnels afin de tenir compte de leurs difficultés liées à la crise sanitaire du coronavirus.

Le report fiscal concerne :
•	les entreprises ou les experts-comptables qui interviennent pour des clients, pour qui il est possible de demander au service des impôts des entreprises le report sans pénalité du règlement de leurs prochaines échéances d'impôts directs (acompte d'impôt sur les sociétés, taxe sur les salaires).
•	Les travailleurs indépendants qui peuvent moduler à tout moment le taux et les acomptes de prélèvement à la source. Il est aussi possible de reporter le paiement des acomptes de prélèvement à la source sur les revenus professionnels d’un mois sur l’autre, jusqu’à trois fois si les acomptes sont mensuels, ou d’un trimestre sur l’autre si les acomptes sont trimestriels.

Afin d'apporter une aide financière aux entreprises en difficulté, une procédure accélérée de remboursement des créances d'impôt sur les sociétés restituables en 2020 est mise en œuvre.

Enfin, la Commission des chefs de services financiers (CCSF) peut accorder aux entreprises qui rencontrent des difficultés financières des délais de paiement pour s’acquitter de leurs dettes fiscales et sociales en toute confidentialité.

Cette cartographie présente les montants associés aux reports d'échéances fiscales projetés au niveau départemental et régional avec une ventilation par secteur d'activité.

Les données utilisées pour ce tableau de bord sont mises à jour de manière hebdomadaire et sont disponibles en open data sur data.gouv.fr.

Données au ....

**Comment by JulienParis** [comment]
Vu. J’ajoute ça à la preprod

**Comment by JulienParis** [comment]
preview ici pour relectures => https://deploy-preview-77--aides-entreprises-covid19.netlify.app/reports
