### ISSUE TITLE
Codes couleurs APE cohérents d'une chart à l'autre

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/dashboard-aides-entreprises#7]
J'ai ajouté dans le backend une couleur pour chaque section APE. 
J'ai généré un fichier json [ici](https://github.com/etalab/dashboard-aides-entreprises/blob/master/backend/json/sections-naf.json)
Celui-ci indique pour chaque section une couleur "color_section".
Il est également possible d'intégrer cette information dans les json principaux "aides-maille-*.json". A toi Julien de me dire ce que tu préfères.

**Comment by JulienParis** [comment]
PR de résolution de cette issue ici => https://github.com/etalab/dashboard-aides-entreprises/pull/56

**Comment by geoffreyaldebert** [comment]
Merci c'est tout bon je close l'issue
