### ISSUE TITLE
échelle categories effectifs constantes OU référentiel classes d'effectifs (taxonomie) avec codes couleurs

### ISSUE THREAD

**Issue by JulienParis** [etalab/dashboard-aides-entreprises#71]

**Comment by geoffreyaldebert** [comment]
hello @JulienParis j'ai ajouté les couleurs dans le master pour les classe effectif. Je close l'issue.

**Comment by JulienParis** [comment]
@geoffreyaldebert je viens de faire un pull du master mais dans le dossier `backend/json/taxonomies/` le fichier `categories-juridiques.json` a des couleurs mais le fichier `classes-effectifs.json` n'en contient pas

**Comment by geoffreyaldebert** [comment]
oups j'ai fait la modif dans le code mais je n'ai pas généré le json. Je le refais désolé.

**Comment by JulienParis** [comment]
@geoffreyaldebert pas de souci :)

**Comment by geoffreyaldebert** [comment]
c'est bon cette fois-ci je close l'issue (en espérant que tu ne la réouvres pas ^^)

**Comment by JulienParis** [comment]
c'est bon ça a l'air de fonctionner 👍 => https://deploy-preview-75--aides-entreprises-covid19.netlify.app/

**Comment by JulienParis** [comment]
On fera une autre issue sur la question du choiix de la palette de couleur : le rouge pour la catégorie "Etablissement non employeur" est peut-être discutable
