### ISSUE TITLE
Mettre un favicon custom

### ISSUE THREAD

**Issue by etienneburdet** [etalab/dashboard-aides-entreprises#85]
Hello ! C'est une toute petit modif, mais je pense qu'un favicon adapté ferait meilleurs effet que celui de Nuxt 😉 Bon courage !

**Comment by JulienParis** [comment]
Réponse un peu tardive mais on a pris en compte votre remarque et ajouté un favicon depuis :))

**Comment by JulienParis** [comment]
test visible ici :  https://aides-entreprises.data.gouv.fr/

fix in commit [c2565011e6742cdcab360bc969353271bc417d8a](https://github.com/etalab/dashboard-aides-entreprises/commit/c2565011e6742cdcab360bc969353271bc417d8a)
